### ISSUE TITLE
Make CI test for integration test with backend

### ISSUE THREAD

**Issue by NicolajNiels1** [Kodeworks/liquidator-frontend#104]
Make CI test for integration test with backend.

_Originally posted by @NicolajNiels1 in https://github.com/Kodeworks/liquidator-frontend/pull/101/files_

**Comment by FredrikAugust** [comment]
I have worked on this all day, and I could not get it to work...

Think I will wait for @kalkins to come back before continuing, as I think it would help a lot to work with the person who originally wrote the code I'm trying to run :)
