### ISSUE TITLE
Add option to create a company when logged in with no companies registered

### ISSUE THREAD

**Issue by FredrikAugust** [Kodeworks/liquidator-frontend#117]
When the user logs in, he/she should not be able to visit `/transactions`, `/company`, etc. before creating a company, as all those pages depend on having a company.

The way I propose to fix this is to only show two paths in the navigation when logged in with no companies;

- `/create-company` which is a page where you can create one
- `/faq` where you can get answers to the frequently asked questions

This way, we don't force anything on them, as they can be added to a company by an owner of that company, and thus use the application without actually creating any companies themselves.

**Comment by FredrikAugust** [comment]
Does this sound like something that would fly with the intelligentsia @NicolajNiels1?

**Comment by NicolajNiels1** [comment]
That could work.
I would propose empty pages with placeholder text which says something about what the page is and that you have to create a company to use it. (a link to create company form should be added)

Kind of like the Issue page on Github looks like when you create a new repo.
![Screenshot 2019-07-31 at 14 18 36](https://user-images.githubusercontent.com/11172710/62211173-2183c800-b39e-11e9-927e-0ac23724b618.png)
