### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by KaizerTilt** [Kodeworks/liquidator-frontend#129]
**As a** user **I want** to log in **so that** I can interact with the companies that I have access to.

### Acceptance Criteria

1. When I perform a log in with the correct credentials, I should be logged in and be allowed to perform actions on the companies and resources that my user is privileged for.
1. When I perform a log in with incorrect credentials, I should be notified of the error and be able to try again.

Please also note:

1. I should not be automatically logged out of the application if I close the web browser or the tab.

**Comment by FredrikAugust** [comment]
Can you perhaps tag these with user story or something, and move them to done when they are completed? If not it will be quite hasslesome to navigate the issues.

**Comment by NicolajNiels1** [comment]
⬆️ What he said.

I'll work on this today. 🙂
