### ISSUE TITLE
Register user account for new user as existing user

### ISSUE THREAD

**Issue by KaizerTilt** [Kodeworks/liquidator-frontend#133]
**As a** user **I want** to register a user account for a new user **so that** he/she can start using the application.

### Acceptance Criteria

1. When I register a new user with an unused email:
   - The user should be created and login credentials should be sent to the new users email.
   - The new user should be able to login with given credentials.

2. When I try registering a new user with an used email:
   - I should be notified that the user already exist.

**Comment by NicolajNiels1** [comment]
Is this still how we are thinking on registering new users? 🤔 	

We do have a Sign Up form implemented.

**Comment by NicolajNiels1** [comment]
I'm closing this in favor of #145.
IMO more information from product owner is needed.
