### ISSUE TITLE
View projected future transactions

### ISSUE THREAD

**Issue by flyrev** [Kodeworks/liquidator-frontend#155]
Create a new page ("Projection"), which shows a bank statement-like list of future transactions. Recurring transactions should not be included yet.

It should start at the first day of the current month, and a maximum of five years into the future. For each transaction, include the `Date`, `Description`, `In`, `Out` and `Available`. An example where there are four transaction added:

| Date            | Description                                        | In     | Out | Available |
| ---------------- | ----------------------------------------------- | ------ | ----- | ------------ |
| 01.09.2019  | That important client paid us again  | 1000 |       | 1000        |
| 03.09.2019  | Haircut                                             |          | 250 | 750         |
| 03.09.2019  | SD card                                           |           | 99   | 651         |
| 15.09.2019  | Another well-deserved payment     | 500    |        | 1151       |

In the first iteration of this page, do not worry about:
- Start-of-month balance. Assume it is zero.
- Displaying recurring transactions.
- Grouping months together.
- Formatting numbers.
- The page becoming long.
- Having a sum at the end.
- Corrections.
- Categories.
- Colors or any other styling for numbers.
- Sorting of transactions within a single day.
- Having the user be able to choose which month is the "start month". Just use the current month.
- Having the user be able to choose the "end date" of the projection. Use five years.
- Currency.

The page should not have "infinite scroll". Load everything up right away, eagerly. :)

**Comment by FredrikAugust** [comment]
May I ask why it should not include recurring transactions? We already had this partially implemented in the now-removed "Balances page", and the logic for it already exists in the application.

**Comment by flyrev** [comment]
I think it would be better to include recurring transactions in a future PR, unless including it is wildly trivial and/or "artificially excluding" it requires a lot of extra work.

It's in the spirit of a PR doing "one thing".

If we get the comments on https://github.com/Kodeworks/liquidator-frontend/pull/157 resolved, the PR merged, and then create a new issue specifically on showing recurring transactions (and their overrides) correctly, we should be good to go in no time. :)

**Comment by FredrikAugust** [comment]
Actually, it was actually a trivial change to include recurring transactions. The code was already there for the transactions page, so I've included it in the PR to come.
