### ISSUE TITLE
Create base/wrapper function for API-calls with access token, that also handles token refresh and automatic logout.

### ISSUE THREAD

**Issue by KaizerTilt** [Kodeworks/liquidator-frontend#58]

**Comment by FredrikAugust** [comment]
Will be fixed by #73. I will create a generic `fetchWithToken` that can be used identically to `fetch`, but will automatically handle expired tokens etc., so that the developer developing a higher level API does not need to care about the underlying business logic at all.

**Comment by FredrikAugust** [comment]
So it will probably be a complete rewrite of [this](https://github.com/Kodeworks/liquidator-frontend/blob/feature/add-transactions/src/mitochondria/index.ts) file (mitochondria/index.ts from feature/add-transactions) to mirror this behaviour.

Furthermore, I don't think having a separate function for `get`, `post`, `put`, etc. is beneficial to the complexity of the mitochondria (felt like a biology professor writing that sentence btw) as it doesn't really require less understanding of the code compared to a generic wrapped `fetch` call as pitched in this issue and #73.

**Comment by FredrikAugust** [comment]
Would like to hear the opinion of @KaizerTilt and @NicolajNiels1 before making any changes.

**Comment by NicolajNiels1** [comment]
> Would like to hear the opinion of @KaizerTilt and @NicolajNiels1 before making any changes.

Forgot to answer this a bit earlier 🙈 , but for the sake of documenting our decision-making 📝: This is supported by me.
