### ISSUE TITLE
Move Balances.tsx to pages/ instead of organism/

### ISSUE THREAD

**Issue by FredrikAugust** [Kodeworks/liquidator-frontend#83]
I believe it would be more suited in the pages folder, as it's a complete page. But if you have any counterarguments for why it should stay in organism/, I'd love to hear them.

Could also use some input from @NicolajNiels1.

**Comment by KaizerTilt** [comment]
As it is used in the application right now I fully agree. However, after discussing with PO there was a suggestion that it would fit better inside the Dashboard page, possibly under it's own tab, so I left it as a organism for the time being.

**Comment by KaizerTilt** [comment]
Actually, regardless if it ends up as a stand-alone page or included in Dashboard I think a page would be best, as it's quite big and unlikely to be used in combination with other components.
I support moving it to pages/.

**Comment by FredrikAugust** [comment]
Sounds good!

**Comment by NicolajNiels1** [comment]
I support this. I have been wondering if some of the"organisms" should rather be pages myself. Glad this was brought up. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FredrikAugust** [comment]
Great. Thanks for the input.
