### ISSUE TITLE
Consistent use of async and sync actions

### ISSUE THREAD

**Issue by NicolajNiels1** [Kodeworks/liquidator-frontend#91]
I notice that there's some inconsistency regarding the use of actions in components. In some places we use dispatch, directly for sync actions:
### Sometimes this
```
dispatch(some_action_creator(args))
```
and for async:
```
Perform.doSomeAsyncAction(somne_args, dispatch)
```

### At other times this
Other times it seems like helper methods are use for sync actions as well:
```
Perform.doSomeSyncActino(some_args,dispatch);
```

I would like to request more consistency and invite to a discussion here. :blush:

**Comment by NicolajNiels1** [comment]
### Example on sync action helper
https://github.com/Kodeworks/liquidator-frontend/blob/464f743c33bf0dbbff1cf4d6e7c843bbec04e3c7/src/store/reducers/auth.ts#L95-L98

### Example on async action helper
https://github.com/Kodeworks/liquidator-frontend/blob/464f743c33bf0dbbff1cf4d6e7c843bbec04e3c7/src/store/reducers/transactions.ts#L37-L46

**Comment by NicolajNiels1** [comment]
> ### Example on sync action helper
> https://github.com/Kodeworks/liquidator-frontend/blob/464f743c33bf0dbbff1cf4d6e7c843bbec04e3c7/src/store/reducers/auth.ts#L95-L98
> 
> ### Example on async action helper
> https://github.com/Kodeworks/liquidator-frontend/blob/464f743c33bf0dbbff1cf4d6e7c843bbec04e3c7/src/store/reducers/transactions.ts#L37-L46

**Note:** Different name conventions above! Other places the second helper would be called doCreateTransaction. I invite @FredrikAugust to elaborate on his naming conventions for clarity.

**Comment by FredrikAugust** [comment]
The idea here is the following - note that there are some inconsistencies as of now, as I changed approach after beginning with async actions. This will be addressed in #90.

All reducers should export an object called `[Name]Actions` which has methods you can use to perform reducer actions. They all take the corresponding `dispatch` as the last argument, and will perform the actual dispatch in the action action creator. These will all have `do` as a prefix, as the non-prefixed versions of them actually create the action that will be dispatched to the reducer.

So the flow will look like this for actions.

In the react code, you call an action like this:

```typescript
TransactionActions.doAddTransaction(transaction, transactionDispatch);
```

Which in turn will call a function in the reducer file that looks like this:

```typescript
const doAddTransaction = (transaction: ITransaction, dispatch: React.Dispatch<Actions>) => {
  // do stuff
  dispatch(addTransaction(transaction));
}
```

`addTransaction(...)` will simply create an action that will be sent to the reducer.

As for the sync/async discussion, I propose keeping them the same - both have a prefix of `do`.

---------------------------------------------
Conclusion;

In the react code, you should only use the `[Name]Actions.do[ActionName]` with `dispatch` as the last argument, to avoid inconsistency, and leave the actual dispatching to the reducer.

**Comment by FredrikAugust** [comment]
Fixed by #90.

**Comment by FredrikAugust** [comment]
Furthermore, all actions that are dispatched to the reducer will have two keys: `payload` and `type`. Type is the type of the action, and payload is the data. This way the code of the reducer is very predictable, and no information is lost, as the variable names to the `do`-functions will be the same.

**Comment by NicolajNiels1** [comment]
> Conclusion;
> 
> In the react code, you should only use the `[Name]Actions.do[ActionName]` with `dispatch` as the last argument, to avoid inconsistency, and leave the actual dispatching to the reducer.

Fantastic! This made it much clearer for me. Thank you!

(only, the `doAddTransaction` would be async 😚 )
