### ISSUE TITLE
Add functionality to delete singular transactions

### ISSUE THREAD

**Issue by NicolajNiels1** [Kodeworks/liquidator-frontend#94]
I'm thinking an icon button appearing when hovering over a transaction with a trash bin.

Clicking on the trashbin triggers a dialog box where the user has to confirm the deletion.

Handling the deletion of recurring transactions will **NOT** be addressed in this issue. For those cases, the users should be prompted to choose whether to delete the particular transaction, all future transactions, all previous transaction or all transactions in the recurring scope.

**Comment by FredrikAugust** [comment]
I will implement the backend for this, i.e. the API implementations.

**Comment by NicolajNiels1** [comment]
> I will implement the backend for this, i.e. the API implementations.

Yes. I'll be working on the visual aspects.
